#!/bin/sh
. $HOME/OpenFOAM/OpenFOAM-v1606+/etc/bashrc

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions
rm -rf comms/OpenFOAM.lock
rm -rf postProcessing
rm -rf processor*
foamListTimes -rm -noZero
rm -rf log.decomposePar
rm -rf log.reconstructPar

#-- Run on single processor
#runApplication $(getApplication) &
# Simulated external solver
#runApplication ./externalSolver

# Decompose
runApplication decomposePar -allRegions

# Run OpenFOAM
runParallel $(getApplication)
